const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const mysql=require('mysql2/promise');const bcrypt=require('bcrypt');
const TEST_DB=process.env.TEST_DB_NAME||'ahifambe_automated_test';const configuredProductionName=process.env.DB_NAME||'ahifambe_db';if(!/test/i.test(TEST_DB)||TEST_DB===configuredProductionName)throw new Error('TEST_DB_NAME must identify a separate test database.');
process.env.DB_NAME=TEST_DB;process.env.NODE_ENV='test';process.env.JWT_SECRET='synthetic-automated-test-secret-not-for-production';process.env.CORS_ORIGINS='https://test.local';process.env.AUTH_RATE_LIMIT_MAX='100';
let root,pool,server,base;const call=async(method,path,token,body,headers={})=>{const options={method,headers:{...headers,...(token?{Authorization:`Bearer ${token}`}:{})}};if(body!==undefined){options.headers['Content-Type']='application/json';options.body=JSON.stringify(body)}const response=await fetch(base+path,options);return{status:response.status,data:await response.json(),headers:response.headers}};
test('complete API regression uses only an isolated database',async(t)=>{require('dotenv').config({path:require('node:path').join(__dirname,'../.env')});root=await mysql.createConnection({host:process.env.DB_HOST,port:process.env.DB_PORT,user:process.env.DB_USER,password:process.env.DB_PASSWORD,multipleStatements:true});await root.query(`DROP DATABASE IF EXISTS ${TEST_DB}`);await root.query(`CREATE DATABASE ${TEST_DB}`);let schema=fs.readFileSync(require('node:path').join(__dirname,'../database/schema.sql'),'utf8').replace(/^CREATE DATABASE[^;]+;\s*USE[^;]+;/i,'');await root.query(`USE ${TEST_DB};${schema}`);const hash=await bcrypt.hash('Strong123!',4);await root.query(`INSERT INTO ${TEST_DB}.users(name,email,password_hash,role,status) VALUES ('Admin','admin@test',?,'admin','active')`,[hash]);const app=require('../src/app'),{generateToken}=require('../src/utils/jwt');server=app.listen(0);await new Promise((resolve)=>server.once('listening',resolve));base=`http://127.0.0.1:${server.address().port}/api`;pool=require('../src/config/db').pool;t.after(async()=>{await new Promise((resolve)=>server.close(resolve));await pool.end();await root.query(`DROP DATABASE IF EXISTS ${TEST_DB}`);await root.end()});
 const admin=generateToken({id:1,email:'admin@test',role:'admin'});
 const registerDriver=await call('POST','/auth/register',null,{name:'Driver One',email:'driver1@test',password:'Strong123!',role:'driver'});assert.equal(registerDriver.status,201);const driver1=registerDriver.data.token;
 const driverTwo=await call('POST','/auth/register',null,{name:'Driver Two',email:'driver2@test',password:'Strong123!',role:'driver'});assert.equal(driverTwo.status,201);const driver2=driverTwo.data.token;
 const passengerOne=await call('POST','/auth/register',null,{name:'Passenger One',email:'passenger1@test',password:'Strong123!',role:'passenger'});assert.equal(passengerOne.status,201);const passenger1=passengerOne.data.token;
 const passengerTwo=await call('POST','/auth/register',null,{name:'Passenger Two',email:'passenger2@test',password:'Strong123!',role:'passenger'});assert.equal(passengerTwo.status,201);const passenger2=passengerTwo.data.token;
 assert.equal((await call('POST','/auth/register',null,{name:'Short',email:'short@test',password:'short',role:'passenger'})).status,400);assert.equal((await call('POST','/auth/login',null,{email:'driver1@test',password:'wrong'})).status,401);assert.equal((await call('POST','/auth/login',null,{email:'driver1@test',password:'Strong123!'})).status,200);assert.equal((await call('GET','/auth/me',driver1)).status,200);assert.equal((await call('GET','/auth/me')).status,401);assert.equal((await call('GET','/users',driver1)).status,403);assert.equal((await call('GET','/users',admin)).status,200);
 const [drivers]=await root.query(`SELECT id,user_id FROM ${TEST_DB}.drivers ORDER BY id`);const createAssets=async(name,plate,driverId,driverToken)=>{const route=await call('POST','/routes',admin,{nome:name,origem:'A',destino:'B',driver_id:driverId});assert.equal(route.status,201);const vehicle=await call('POST','/vehicles',driverToken,{plate_number:plate,model:'Test',capacity:12,status:'active',driver_id:999999});assert.equal(vehicle.status,201);assert.equal(Number(vehicle.data.vehicle.driver_id),Number(driverId));return{route:route.data.route,vehicle:vehicle.data.vehicle}};
 const a1=await createAssets('Route One','AUTO-1',drivers[0].id,driver1),a2=await createAssets('Route Two','AUTO-2',drivers[1].id,driver2);assert.equal((await call('GET','/routes',driver1)).data.some((r)=>r.id===a2.route.id),false);assert.equal((await call('GET','/vehicles',driver1)).data.some((v)=>v.id===a2.vehicle.id),false);assert.equal((await call('PUT',`/vehicles/${a1.vehicle.id}`,driver2,{plate_number:'STOLEN',model:'No',capacity:2,status:'active'})).status,403);assert.equal((await call('POST','/vehicles',admin,{plate_number:'ADMIN-1',model:'No',capacity:2})).status,403);assert.equal((await call('POST','/vehicles',passenger1,{plate_number:'PASS-1',model:'No',capacity:2})).status,403);assert.equal((await call('POST','/vehicles',driver1,{plate_number:'AUTO-1',model:'Duplicate',capacity:2})).status,409);assert.equal((await call('POST','/vehicles',driver1,{plate_number:'BAD-CAP',model:'Invalid',capacity:0})).status,400);const adminVehicles=await call('GET','/vehicles',admin);assert.equal(adminVehicles.status,200);assert.equal(adminVehicles.data.some((v)=>v.id===a1.vehicle.id),true);const adminEdit=await call('PUT',`/vehicles/${a1.vehicle.id}`,admin,{plate_number:'AUTO-1',model:'Admin edited',capacity:13,status:'active',driver_id:drivers[0].id});assert.equal(adminEdit.status,200);assert.equal(adminEdit.data.vehicle.model,'Admin edited');
 const disposable=await call('POST','/vehicles',driver1,{plate_number:'TEMP-1',model:'Temporary',capacity:3});assert.equal(disposable.status,201);const disposableId=disposable.data.vehicle.id;assert.equal((await call('PUT',`/vehicles/${disposableId}`,driver1,{plate_number:'TEMP-1',model:'Edited by owner',capacity:4,status:'active',driver_id:drivers[1].id})).data.vehicle.driver_id,drivers[0].id);assert.equal((await call('DELETE',`/vehicles/${disposableId}`,driver2)).status,403);assert.equal((await call('DELETE',`/vehicles/${disposableId}`,driver1)).status,200);assert.equal((await call('PUT','/vehicles/not-an-id',driver1,{plate_number:'X',model:'X',capacity:1,status:'active'})).status,400);
 const start=await call('POST','/trips/start',driver1,{route_id:a1.route.id,vehicle_id:a1.vehicle.id});assert.equal(start.status,201);const tripId=start.data.trip.id;assert.equal((await call('POST','/trips/start',driver1,{route_id:a1.route.id,vehicle_id:a1.vehicle.id})).status,409);assert.equal((await call('POST','/trips/start',driver1,{route_id:a2.route.id,vehicle_id:a1.vehicle.id})).status,409);assert.equal((await call('PATCH',`/vehicles/${a1.vehicle.id}/status`,admin,{status:'inactive'})).status,409);assert.equal((await call('PATCH',`/vehicles/${a1.vehicle.id}/status`,driver1,{status:'maintenance'})).status,409);assert.equal((await call('DELETE',`/vehicles/${a1.vehicle.id}`,driver1)).status,409);assert.equal((await call('DELETE',`/routes/${a1.route.id}`,admin)).status,409);
 assert.equal((await call('PATCH',`/trips/${tripId}/status`,driver1,{lotacao:'lotado'})).status,200);assert.equal((await call('POST','/locations/update',driver1,{trip_id:tripId,latitude:-25.96,longitude:32.58})).status,201);assert.equal((await call('PATCH',`/trips/${tripId}/end`,driver2)).status,403);
 const active=await call('GET','/trips/active',passenger1);assert.equal(active.status,200);assert.equal(active.data[0].lotacao,'lotado');assert.equal(Number(active.data[0].latitude),-25.96);
 const request=await call('POST','/ride-requests',passenger1,{trip_id:tripId,passenger_latitude:-25.95,passenger_longitude:32.57,destination:'Stop',people_count:1});assert.equal(request.status,201);assert.equal((await call('POST','/ride-requests',passenger1,{trip_id:tripId,passenger_latitude:-25.95,passenger_longitude:32.57,destination:'Stop',people_count:1})).status,409);assert.equal((await call('GET','/ride-requests/passenger',passenger2)).data.length,0);assert.equal((await call('PATCH',`/ride-requests/${request.data.ride_request.id}/accept`,driver2)).status,403);
 assert.equal((await call('POST','/feedback',passenger1,{type:'sugestao',message:'Synthetic feedback'})).status,201);const endings=await Promise.all([call('PATCH',`/trips/${tripId}/end`,driver1),call('PATCH',`/trips/${tripId}/end`,driver1)]);assert.deepEqual(endings.map((r)=>r.status).sort(),[200,409]);assert.equal((await call('GET','/trips/active',passenger1)).data.length,0);assert.equal((await call('POST','/ride-requests',passenger2,{trip_id:tripId,passenger_latitude:-25,passenger_longitude:32,destination:'X',people_count:1})).status,409);
 const monitoring=await call('GET','/trips?status=finished&page=1&limit=20',admin);assert.equal(monitoring.status,200);assert.equal(monitoring.data.pagination.total,1);assert.equal((await call('GET','/trips',passenger1)).status,403);assert.equal((await call('GET','/health',null,undefined,{Origin:'https://test.local'})).status,200);assert.equal((await call('GET','/health',null,undefined,{Origin:'https://blocked.test'})).status,403);
});
test('finished migration preserves legacy states and can be repeated',async()=>{
  require('dotenv').config({path:require('node:path').join(__dirname,'../.env')});
  const migrationDb=`${TEST_DB}_migration`;
  if(!/test/i.test(migrationDb))throw new Error('Unsafe migration test database name.');
  const connection=await mysql.createConnection({host:process.env.DB_HOST,port:process.env.DB_PORT,user:process.env.DB_USER,password:process.env.DB_PASSWORD,multipleStatements:true});
  try{
    await connection.query(`DROP DATABASE IF EXISTS ${migrationDb};CREATE DATABASE ${migrationDb};USE ${migrationDb};CREATE TABLE trips(id INT AUTO_INCREMENT PRIMARY KEY,status ENUM('scheduled','in_progress','completed','cancelled') NOT NULL DEFAULT 'scheduled');INSERT INTO trips(status) VALUES('completed')`);
    const migration=fs.readFileSync(require('node:path').join(__dirname,'../database/add_trips_finished_status.sql'),'utf8');
    await connection.query(migration);await connection.query(migration);
    await connection.query("INSERT INTO trips(status) VALUES('finished')");
    const [rows]=await connection.query('SELECT status FROM trips ORDER BY id');
    assert.deepEqual(rows.map((row)=>row.status),['completed','finished']);
  }finally{await connection.query(`DROP DATABASE IF EXISTS ${migrationDb}`);await connection.end()}
});