const { pool } = require('../config/db');
const create = async ({ passenger_id, driver_id, trip_id, passenger_latitude, passenger_longitude, destination, people_count, note }) => {
  const [result] = await pool.execute(`INSERT INTO ride_requests (passenger_id,driver_id,trip_id,passenger_latitude,passenger_longitude,destination,people_count,note,status) VALUES (?,?,?,?,?,?,?,?,'pending')`, [passenger_id,driver_id,trip_id,passenger_latitude,passenger_longitude,destination,people_count,note || null]);
  return result.insertId;
};
const findById = async (id) => { const [rows] = await pool.execute('SELECT id,passenger_id,driver_id,trip_id,passenger_latitude,passenger_longitude,destination,people_count,note,status,created_at,updated_at FROM ride_requests WHERE id=? LIMIT 1',[id]); return rows[0] || null; };
const findTripById = async (id) => { const [rows] = await pool.execute('SELECT id,driver_id,route_id,status FROM trips WHERE id=? LIMIT 1',[id]); return rows[0] || null; };
const findPassengerByUserId = async (id) => { const [rows] = await pool.execute('SELECT id,user_id FROM passengers WHERE user_id=? LIMIT 1',[id]); return rows[0] || null; };
const findDriverByUserId = async (id) => { const [rows] = await pool.execute('SELECT id,user_id FROM drivers WHERE user_id=? LIMIT 1',[id]); return rows[0] || null; };
const findPendingDuplicate = async (passengerId, tripId) => { const [rows] = await pool.execute("SELECT id FROM ride_requests WHERE passenger_id=? AND trip_id=? AND status='pending' LIMIT 1",[passengerId,tripId]); return rows[0] || null; };
const findForDriver = async (driverId) => { const [rows] = await pool.execute(`SELECT rr.id,u.name AS passenger_name,rr.passenger_latitude,rr.passenger_longitude,rr.destination,rr.people_count,rr.note,rr.status,rr.trip_id,rr.created_at FROM ride_requests rr INNER JOIN passengers p ON p.id=rr.passenger_id INNER JOIN users u ON u.id=p.user_id WHERE rr.driver_id=? AND rr.status IN ('pending','accepted') ORDER BY rr.created_at DESC`,[driverId]); return rows; };
const findForPassenger = async (passengerId) => { const [rows] = await pool.execute(`SELECT rr.id,rr.destination,rr.people_count,rr.note,rr.status,rr.trip_id,rr.created_at,rr.updated_at,r.nome AS route_nome,r.origem,r.destino AS route_destino,v.plate_number,v.model FROM ride_requests rr INNER JOIN trips t ON t.id=rr.trip_id INNER JOIN routes r ON r.id=t.route_id LEFT JOIN vehicles v ON v.id=t.vehicle_id WHERE rr.passenger_id=? ORDER BY rr.created_at DESC`,[passengerId]); return rows; };
const updateStatus = async (id,status) => { const [result] = await pool.execute("UPDATE ride_requests SET status=? WHERE id=? AND status='pending'",[status,id]); return result.affectedRows; };
module.exports={create,findById,findTripById,findPassengerByUserId,findDriverByUserId,findPendingDuplicate,findForDriver,findForPassenger,updateStatus};