const rideRequestModel = require('../models/rideRequestModel');
const AppError = require('../utils/AppError');
const normalizeId = (value) => { const id=Number(value); return Number.isInteger(id)&&id>0?id:null; };
const normalizeCoordinate = (value) => { if(value===null||value===undefined||value==='') return null; const coordinate=Number(value); return Number.isFinite(coordinate)?coordinate:null; };
const getPassengerForUser = async (value) => { const id=normalizeId(value); if(!id) throw new AppError('Authenticated user is required.',401); const passenger=await rideRequestModel.findPassengerByUserId(id); if(!passenger) throw new AppError('Passenger profile not found for authenticated user.',404); return passenger; };
const getDriverForUser = async (value) => { const id=normalizeId(value); if(!id) throw new AppError('Authenticated user is required.',401); const driver=await rideRequestModel.findDriverByUserId(id); if(!driver) throw new AppError('Driver profile not found for authenticated user.',404); return driver; };
const createRideRequest = async (input) => {
  const passenger=await getPassengerForUser(input.user_id), trip_id=normalizeId(input.trip_id);
  const passenger_latitude=normalizeCoordinate(input.passenger_latitude), passenger_longitude=normalizeCoordinate(input.passenger_longitude);
  const destination=String(input.destination||'').trim(), people_count=Number(input.people_count), note=String(input.note||'').trim();
  if(!trip_id) throw new AppError('trip_id is required and must be a valid id.',400);
  if(passenger_latitude===null||passenger_latitude < -90||passenger_latitude > 90) throw new AppError('passenger_latitude must be a valid coordinate.',400);
  if(passenger_longitude===null||passenger_longitude < -180||passenger_longitude > 180) throw new AppError('passenger_longitude must be a valid coordinate.',400);
  if(!destination) throw new AppError('destination is required.',400);
  if(!Number.isInteger(people_count)||people_count<=0) throw new AppError('people_count is required and must be greater than 0.',400);
  const trip=await rideRequestModel.findTripById(trip_id);
  if(!trip) throw new AppError('Trip not found.',404);
  if(trip.status!=='in_progress') throw new AppError('Trip must be in progress to receive ride requests.',409);
  if(await rideRequestModel.findPendingDuplicate(passenger.id,trip_id)) throw new AppError('A pending ride request already exists for this trip.',409);
  const id=await rideRequestModel.create({passenger_id:passenger.id,driver_id:trip.driver_id,trip_id,passenger_latitude,passenger_longitude,destination,people_count,note});
  const created=await rideRequestModel.findById(id);
  return {message:'Ride request created successfully.',ride_request:{id:created.id,trip_id:created.trip_id,destination:created.destination,people_count:created.people_count,note:created.note,status:created.status,created_at:created.created_at}};
};
const listDriverRequests=async(userId)=>rideRequestModel.findForDriver((await getDriverForUser(userId)).id);
const listPassengerRequests=async(userId)=>rideRequestModel.findForPassenger((await getPassengerForUser(userId)).id);
const updateDriverRequestStatus=async(idInput,userId,status)=>{const id=normalizeId(idInput),driver=await getDriverForUser(userId);if(!id)throw new AppError('Ride request id must be a valid id.',400);const request=await rideRequestModel.findById(id);if(!request)throw new AppError('Ride request not found.',404);if(Number(request.driver_id)!==Number(driver.id))throw new AppError('Driver does not own this ride request.',403);if(request.status!=='pending')throw new AppError('Only pending ride requests can be updated.',409);if(await rideRequestModel.updateStatus(id,status)!==1)throw new AppError('Ride request is no longer pending.',409);return {message:`Ride request ${status} successfully.`,ride_request:await rideRequestModel.findById(id)}};
module.exports={createRideRequest,listDriverRequests,listPassengerRequests,updateDriverRequestStatus};