import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import L from 'leaflet'
import { MapContainer, Marker, Popup, TileLayer, useMap } from 'react-leaflet'
import markerIcon2x from 'leaflet/dist/images/marker-icon-2x.png'
import markerIcon from 'leaflet/dist/images/marker-icon.png'
import markerShadow from 'leaflet/dist/images/marker-shadow.png'
import { useAuth } from '../../context/AuthContext'
import { createFeedback } from '../../services/feedbackService'
import { createRideRequest, getPassengerRideRequests } from '../../services/rideRequestService'
import { getActiveTrips } from '../../services/tripService'

const MAPUTO_CENTER=[-25.9655,32.5832]
const occupancy={vazio:'Vazio',intermedio:'Intermédio',lotado:'Lotado'}
const requestStatus={pending:'Pendente',accepted:'Aceite',rejected:'Rejeitado'}
L.Icon.Default.mergeOptions({iconRetinaUrl:markerIcon2x,iconUrl:markerIcon,shadowUrl:markerShadow})
const icons=Object.fromEntries(Object.keys(occupancy).map((value)=>[value,L.divIcon({className:`passenger-marker passenger-marker-${value}`,html:'<span></span>',iconAnchor:[12,24],iconSize:[24,24],popupAnchor:[0,-24]})]))
const formatDate=(value)=>value?new Intl.DateTimeFormat('pt-MZ',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'-'
const locationState=(trip)=>{if(!trip.location_updated_at)return 'Indisponível';return Date.now()-new Date(trip.location_updated_at).getTime()<=120000?'Recente':'Antiga'}
const validCoordinate=(lat,lng)=>Number.isFinite(lat)&&Number.isFinite(lng)&&lat>=-90&&lat<=90&&lng>=-180&&lng<=180
function MapBounds({trips}){const map=useMap();useEffect(()=>{const points=trips.map((t)=>[t.latitude,t.longitude]);if(points.length===1)map.setView(points[0],14);else if(points.length>1)map.fitBounds(points,{padding:[36,36]})},[map,trips]);return null}
const getPosition=()=>new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,maximumAge:10000,timeout:15000}))

function PassengerDashboard(){
 const {logout,user}=useAuth();const [trips,setTrips]=useState([]),[requests,setRequests]=useState([]),[route,setRoute]=useState('all');const [loadingTrips,setLoadingTrips]=useState(true),[loadingRequests,setLoadingRequests]=useState(true);const [error,setError]=useState(''),[requestError,setRequestError]=useState(''),[success,setSuccess]=useState('');const [selected,setSelected]=useState(null),[form,setForm]=useState({destination:'',people_count:'1',note:''}),[submitting,setSubmitting]=useState(false);const [feedbackOpen,setFeedbackOpen]=useState(false),[feedback,setFeedback]=useState({type:'reclamacao',message:''}),[feedbackSaving,setFeedbackSaving]=useState(false);const tripsBusy=useRef(false),requestsBusy=useRef(false)
 const loadTrips=useCallback(async(quiet=false)=>{if(tripsBusy.current)return;tripsBusy.current=true;if(!quiet)setLoadingTrips(true);try{const data=await getActiveTrips();setTrips(data.map((item)=>({...item,latitude:Number(item.latitude),longitude:Number(item.longitude),lotacao:occupancy[item.lotacao]?item.lotacao:'vazio'})));setError('')}catch(e){setError(e.response?.data?.message||'Não foi possível carregar as viagens activas.')}finally{tripsBusy.current=false;if(!quiet)setLoadingTrips(false)}},[])
 const loadRequests=useCallback(async(quiet=false)=>{if(requestsBusy.current)return;requestsBusy.current=true;if(!quiet)setLoadingRequests(true);try{setRequests(await getPassengerRideRequests());setRequestError('')}catch(e){setRequestError(e.response?.data?.message||'Não foi possível carregar os pedidos.')}finally{requestsBusy.current=false;if(!quiet)setLoadingRequests(false)}},[])
 useEffect(()=>{const timer=window.setTimeout(()=>{loadTrips();loadRequests()},0);return()=>window.clearTimeout(timer)},[loadTrips,loadRequests])
 useEffect(()=>{const timer=window.setInterval(()=>{if(document.visibilityState==='visible'){loadTrips(true);if(requests.some((r)=>r.status==='pending'))loadRequests(true)}},20000);return()=>window.clearInterval(timer)},[loadTrips,loadRequests,requests])
 const routes=useMemo(()=>[...new Set(trips.map((t)=>t.route_name))],[trips]);const visible=useMemo(()=>route==='all'?trips:trips.filter((t)=>t.route_name===route),[route,trips]);const mapped=useMemo(()=>visible.filter((t)=>validCoordinate(t.latitude,t.longitude)),[visible])
 const openRequest=(trip)=>{setSelected(trip);setForm({destination:trip.destination||'',people_count:'1',note:''});setError('');setSuccess('')}
 const submitRequest=async(e)=>{e.preventDefault();if(submitting)return;if(!('geolocation'in navigator)){setError('A geolocalização não está disponível neste navegador.');return}setSubmitting(true);setError('');try{const position=await getPosition();const result=await createRideRequest({trip_id:selected.trip_id,passenger_latitude:position.coords.latitude,passenger_longitude:position.coords.longitude,destination:form.destination.trim(),people_count:Number(form.people_count),note:form.note.trim()||undefined});setRequests((items)=>[result.ride_request,...items]);setSelected(null);setSuccess('Pedido enviado ao motorista.')}catch(err){setError(err.response?.data?.message||err.message||'Não foi possível enviar o pedido.')}finally{setSubmitting(false)}}
 const submitFeedback=async(e)=>{e.preventDefault();setFeedbackSaving(true);setError('');try{await createFeedback({type:feedback.type,message:feedback.message.trim()});setFeedbackOpen(false);setFeedback({type:'reclamacao',message:''});setSuccess('Feedback enviado ao administrador.')}catch(err){setError(err.response?.data?.message||'Não foi possível enviar o feedback.')}finally{setFeedbackSaving(false)}}
 return <main className="passenger-page">
  <header className="passenger-header"><div><span className="eyebrow">Painel do passageiro</span><h1>Olá, {user?.name||'passageiro'}</h1><p>Acompanhe viagens activas e os seus pedidos.</p></div><div className="passenger-header-actions"><span className="passenger-live-status">{loadingTrips?'A actualizar...':`${visible.length} viagens activas`}</span><button className="button" onClick={()=>setFeedbackOpen(true)} type="button">Enviar feedback</button><button className="button button-secondary" onClick={logout} type="button">Logout</button></div></header>
  {error?<div className="passenger-error">{error}</div>:null}{success?<div className="passenger-success">{success}</div>:null}
  <section className="passenger-toolbar"><label className="passenger-field"><span>Filtrar por rota</span><select onChange={(e)=>setRoute(e.target.value)} value={route}><option value="all">Todas as rotas</option>{routes.map((name)=><option key={name} value={name}>{name}</option>)}</select></label><button className="button" disabled={loadingTrips} onClick={()=>loadTrips()} type="button">Actualizar agora</button></section>
  <section className="passenger-grid"><aside className="passenger-panel"><div className="passenger-panel-header"><div><span className="eyebrow">Viagens activas</span><strong>{visible.length}</strong></div></div>{loadingTrips?<div className="passenger-state">A carregar viagens...</div>:null}{!loadingTrips&&!visible.length?<div className="passenger-state">Não existem viagens activas neste momento.</div>:null}<div className="passenger-chapa-list">{visible.map((trip)=><article className="passenger-chapa-card" key={trip.trip_id}><span>{trip.route_name}</span><strong>{trip.plate_number||'Matrícula indisponível'}</strong><small>{trip.model||'Modelo indisponível'} · capacidade {trip.capacity??'-'}</small><small className={`passenger-lotacao passenger-lotacao-${trip.lotacao}`}>Lotação: {occupancy[trip.lotacao]}</small><p>{trip.origin} para {trip.destination}</p><small>Partida: {formatDate(trip.departure_time)}</small><small>Localização: {locationState(trip)}{trip.location_updated_at?` · ${formatDate(trip.location_updated_at)}`:''}</small><button className="button passenger-request-button" onClick={()=>openRequest(trip)} type="button">Requisitar Chapa</button></article>)}</div></aside>
   <section className="passenger-map-panel">{mapped.length?<MapContainer center={MAPUTO_CENTER} className="passenger-map" scrollWheelZoom zoom={12}><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><MapBounds trips={mapped}/>{mapped.map((trip)=><Marker icon={icons[trip.lotacao]} key={trip.trip_id} position={[trip.latitude,trip.longitude]}><Popup><div className="passenger-popup"><strong>{trip.route_name}</strong><span>Matrícula: {trip.plate_number||'-'}</span><span>Lotação: {occupancy[trip.lotacao]}</span><span>Localização: {locationState(trip)}</span><button className="button passenger-request-button" onClick={()=>openRequest(trip)} type="button">Requisitar Chapa</button></div></Popup></Marker>)}</MapContainer>:<div className="passenger-state">Esta viagem ainda não possui localização disponível.</div>}</section>
   <aside className="passenger-panel"><div className="passenger-panel-header"><div><span className="eyebrow">Meus pedidos</span><strong>{requests.length}</strong></div></div>{requestError?<div className="passenger-error">{requestError}</div>:null}{loadingRequests?<div className="passenger-state">A carregar pedidos...</div>:null}{!loadingRequests&&!requests.length?<div className="passenger-state">Ainda não efectuou nenhum pedido.</div>:null}<div className="passenger-chapa-list">{requests.map((item)=><article className="passenger-chapa-card" key={item.id}><span>{item.route_nome||`Viagem #${item.trip_id}`}</span><strong>{item.destination}</strong><small>{item.plate_number||'Viatura indisponível'} · {item.people_count} passageiro(s)</small><small className={`admin-status-badge ${item.status==='accepted'?'admin-status-active':'admin-status-blocked'}`}>{requestStatus[item.status]||item.status}</small><small>{formatDate(item.created_at)}</small>{item.note?<p>{item.note}</p>:null}</article>)}</div></aside>
  </section>
  {selected?<div className="passenger-modal-backdrop" role="presentation"><form className="passenger-request-modal" onSubmit={submitRequest} role="dialog"><div className="passenger-panel-header"><div><span className="eyebrow">Pedido de chapa</span><strong>{selected.route_name}</strong></div><button className="driver-modal-close" disabled={submitting} onClick={()=>setSelected(null)} type="button">×</button></div><div className="passenger-request-modal-body"><p>{selected.plate_number} · {selected.origin} para {selected.destination}</p><label className="passenger-field"><span>Destino</span><input required value={form.destination} onChange={(e)=>setForm((v)=>({...v,destination:e.target.value}))}/></label><label className="passenger-field"><span>Número de pessoas</span><input min="1" required type="number" value={form.people_count} onChange={(e)=>setForm((v)=>({...v,people_count:e.target.value}))}/></label><label className="passenger-field"><span>Observação opcional</span><textarea rows="3" value={form.note} onChange={(e)=>setForm((v)=>({...v,note:e.target.value}))}/></label></div><div className="driver-actions passenger-request-actions"><button className="button" disabled={submitting} type="submit">{submitting?'A enviar...':'Enviar pedido'}</button><button className="button button-secondary" disabled={submitting} onClick={()=>setSelected(null)} type="button">Cancelar</button></div></form></div>:null}
  {feedbackOpen?<div className="passenger-modal-backdrop" role="presentation"><form className="passenger-request-modal" onSubmit={submitFeedback} role="dialog"><div className="passenger-panel-header"><strong>Enviar feedback</strong><button className="driver-modal-close" disabled={feedbackSaving} onClick={()=>setFeedbackOpen(false)} type="button">×</button></div><div className="passenger-request-modal-body"><label className="passenger-field"><span>Tipo</span><select value={feedback.type} onChange={(e)=>setFeedback((v)=>({...v,type:e.target.value}))}><option value="reclamacao">Reclamação</option><option value="sugestao">Sugestão</option><option value="elogio">Elogio</option></select></label><label className="passenger-field"><span>Mensagem</span><textarea required rows="5" value={feedback.message} onChange={(e)=>setFeedback((v)=>({...v,message:e.target.value}))}/></label></div><div className="driver-actions"><button className="button" disabled={feedbackSaving} type="submit">Enviar</button></div></form></div>:null}
 </main>
}
export default PassengerDashboard