const express = require('express');
const vehicleController = require('../controllers/vehicleController');
const { authenticate, authorize } = require('../middlewares/authMiddleware');
const asyncHandler = require('../utils/asyncHandler');
const router = express.Router();
router.use(authenticate);
router.get('/', authorize('admin', 'driver'), asyncHandler(vehicleController.listVehicles));
router.post('/', authorize('admin'), asyncHandler(vehicleController.createVehicle));
router.put('/:id', authorize('admin'), asyncHandler(vehicleController.updateVehicle));
router.patch('/:id/status', authorize('admin'), asyncHandler(vehicleController.updateVehicleStatus));
router.delete('/:id', authorize('admin'), asyncHandler(vehicleController.deleteVehicle));
module.exports = router;